name: Deploy Pipelines - PROD

on:
  workflow_dispatch:

jobs:
  deploy_on_prod:
    uses: ./.github/workflows/deploy-pipelines.yaml
    name: Deploy on PROD
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-assets-cdn-rg'
      app_name: 'io-p-assets-cdn-fn'
      use_staging_slot: true
      use_private_agent: false